# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-23 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20190822_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackname', models.CharField(max_length=100)),
                ('feedbackrating', models.IntegerField()),
                ('feedbackdate', models.DateTimeField(max_length=100)),
                ('feedbackmsg', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='servicesdata',
            name='course_starttime',
            field=models.TimeField(),
        ),
    ]
