# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-27 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_auto_20190823_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdata',
            name='feedbackrating',
            field=models.CharField(max_length=100),
        ),
    ]
